# env vars
LOAD_DB_DATA: 0
RESTAURANT_DATA_URL: https://gist.githubusercontent.com/seahyc/b9ebbe264f8633a1bf167cc6a90d4b57/raw/021d2e0d2c56217bad524119d1c31419b2938505/restaurant_with_menu.json
USER_DATA_URL: https://gist.githubusercontent.com/seahyc/de33162db680c3d595e955752178d57d/raw/785007bc91c543f847b87d705499e86e16961379/users_with_purchase_history.json

DB_ADDRESS: 127.0.0.1:3306
DB_URL: r2dbc:pool:mysql://${DB_ADDRESS}/demo
DB_USERNAME: root
DB_PASSWORD: root
#DB_URL: jdbc:postgresql://127.0.0.1:5432/demo
#DB_USERNAME: postgres
#DB_PASSWORD: postgres
DDL_AUTO: none

logging:
  file:
    name: ./log/fd.log
  level:
    idv: DEBUG
    org.springframework.data.r2dbc: DEBUG

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  metrics:
    web.server.request.autotime.enabled: true

server:
  compression:
    enabled: true
    min-response-size: 1024
  http2:
    enabled: true
  shutdown: graceful

spring:
  application.name: food-delivery
  main:
    banner-mode: 'off'
  webflux:
    static-path-pattern: /static/**
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /api-docs